---
title: "Introduction to dplyr, including how to interact with databases"
author: "Karthik Ram"
date: "July 26, 2014"
output: pdf_document
---


```{r, echo = FALSE, message = FALSE}
# For those who have asked, this is just my way of setting global options to the chunks remaining in the document
# I can still override one or more of these anytime
knitr::opts_chunk$set(
  comment = " ",
  error = FALSE,
  message = FALSE,
  tidy = FALSE
)
```


Manipulating and munging data just became considerably easier in `R` thanks to the `dplyr` package developed by Hadley Wickham.

```{r dplyr}
library(dplyr)
x <- iris %>%  
group_by(Species) %>%
summarise(smallest_sepal = min(Sepal.Length), largest_sepal = max(Sepal.Length)) 
```

You can also coerce this into a `data.frame` like so:

```{r data.frame}
data.frame(x)
```

Need to check to make sure there are even samples across all species?

```{r even_samples}
y <- iris %>% group_by(Species) %>% summarise(sample_size = n())
y
```

More complex select operations

```{r select}
iris <- tbl_df(iris) # so it prints a little nicer
select(iris, starts_with("Petal"))
select(iris, ends_with("Width"))
select(iris, contains("etal"))
select(iris, Petal.Length, Petal.Width)
```



